### ISSUE TITLE
unable to open ssh connection if username has dot in name

### ISSUE THREAD

**Issue by heino-vdbh** [deanishe/alfred-ssh#10]
Hi,

I am unable to connect to servers with "ssh user.name@1.1.1.1"
Without the dot in the username it works.

I use workflow v0.8.0 and iTerm 3.1.6
With MacOS Terminal it works

Best regards
Heino

**Comment by deanishe** [comment]
By all appearances, it's an iTerm bug.

This works:

```bash
open -a Terminal ssh://dave.smith@example.com
```

This doesn't:

```bash
open -a iTerm ssh://dave.smith@example.com
```

As a workaround, you can set `SSH_CMD` to `ssh` in the workflow's settings. That will cause the workflow to generate an `ssh` shell command instead of an `ssh://` URL.

**Comment by deanishe** [comment]
I've [opened an issue](https://gitlab.com/gnachman/iterm2/issues/6720) on the iTerm bugtracker.
