### ISSUE TITLE
Set a ssh/mosh command

### ISSUE THREAD

**Issue by oscarmlage** [deanishe/alfred-ssh#13]
Is there any way to set a ssh/mosh default command as `tmux` or similar?. I mean, when I type `ssh remotehost` in Alfred what I would like is to get something like `mosh remotehost -- tmux`. Dunno if it can be setted in `MOSH_CMD` but I guess it can't.

Any tip?

**Comment by deanishe** [comment]
> but I guess it can't.

Why don’t you try it and find out?

**Comment by oscarmlage** [comment]
Because I don't know the host variable to insert in `MOSH_CMD`. I mean if I would like to execute `mosh host -- whatever`, what's the `host` variable?

**Comment by deanishe** [comment]
There is no `host` variable. The (username and) hostname are appended to whatever command you specify.

**Comment by deanishe** [comment]
I've had a look at the source code again and [I can't simply turn `MOSH_CMD` into a template, I'm afraid](https://github.com/deanishe/alfred-ssh/blob/80f7cc2b648e9acfd147dbd89f874b2b6dfbd7a6/hosts.go#L223).

You could either point `MOSH_CMD` and/or `SSH_CMD` to a custom script that appends your custom arguments to the command, or edit the workflow and add your remote command there.

If you edit the light blue Terminal Command element in the workflow and change the Command to `{query} -- tmux`, that should do the trick.
