### ISSUE TITLE
add an option to read ~/.ssh/config

### ISSUE THREAD

**Issue by ctf0** [deanishe/alfred-ssh#2]
this is easier as the user can have memorable/editable config for the hosts he connects to.

**Comment by isometry** [comment]
~/.ssh/config is already parsed. Can you provide a snippet that you don't believe is being read?

**Comment by ctf0** [comment]
the config file

``` shell
Host *
    ServerAliveInterval 60
    ServerAliveCountMax 120

Host abc
  HostName 00.00.000.000
  User forge
```

and here a ss after disabling both of the other host files
![screen shot 2016-08-12 at 1 44 21 pm](https://cloud.githubusercontent.com/assets/7388088/17621370/19a8a936-6093-11e6-9a7f-12baf5367d97.jpg)

**Comment by deanishe** [comment]
`~/.ssh/config` currently isn't parsed. I need to alter the data model to support it, but it's definitely coming.

**Comment by ctf0** [comment]
sweet 💯

**Comment by isometry** [comment]
Oops. Thought this was a ticket on my ssh workflow, which has always supported parsing all the obvious sources. Apologies for the noise.

**Comment by deanishe** [comment]
:D I thought that might be what happened. I had to check if it was yours or mine.

@ctf0 unless you need the SFTP/ping feature of this workflow, you should look at @isometry's [SSH workflow](https://github.com/isometry/alfredworkflows/tree/master/net.isometry.alfred.ssh), as he says it supports `~/.ssh/config` and it now works with Alfred 3, I think.

**Comment by ctf0** [comment]
yeah i already went with it but it doesn't have the option to exclude the host files which create lots of noise for those who don't need it.

**Comment by isometry** [comment]
@ctf0 if you want to disable hosts in my workflow, simply comment out [line 144](https://github.com/isometry/alfredworkflows/blob/master/net.isometry.alfred.ssh/alfredssh.py#L144) (`fetch_hosts('/etc/hosts'),`) in `alfredssh.py`. You can find it via Open in Finder from the Workflows listing.

**Comment by ctf0** [comment]
@isometry thanx for the tip 👍

**Comment by deanishe** [comment]
Added parsing of `~/.ssh/config` in [v0.5](https://github.com/deanishe/alfred-ssh/releases/tag/v0.5.0). Also now supports using `mosh` instead of `ssh`.
