### ISSUE TITLE
macOS Catalina attempts to delete the executable

### ISSUE THREAD

**Issue by andreiborisov** [deanishe/alfred-ssh#25]
<img width="532" alt="Screenshot 2019-10-08 at 03 50 01" src="https://user-images.githubusercontent.com/13354491/66359379-8c91e200-e97f-11e9-8675-9fc1728a664d.png">

macOS tries to delete the executable, if you click `Cancel` and then `Allow Anyway` inside System Preferences after that, it deletes the executable silently on the next try (oh, Apple).

Mirror issue for Alfred Sublime Text workflow: https://github.com/deanishe/alfred-sublime-text/issues/20

**Comment by andreiborisov** [comment]
Instructions from @jefftriplett on how to fix this issue:

> System Preferences >> Security & Privacy >> General
> Click the 🔒 to allow changes
> Then check out the Allow apps downloaded from: [x] App Store and identified developers
> Restart Alfred
> Try the workflow again
> Back out of Security & Privacy
> Re-enter Security & Privacy
> There should now be an Allow alfsubl option which you'll want to allow
> Restart Alfred again
> Try the workflow again and repeat the steps 6+ as needed.

**Comment by alexcrawford** [comment]
Should this be added to the installation instructions since this is likely affecting everyone?

**Comment by deanishe** [comment]
I've been waiting to see if anyone figures out a less complicated way of getting it to work.

**Comment by andreiborisov** [comment]
Perhaps adding Alfred to the list of Developer Tools in Security & Privacy settings would also fix this?

Not sure you can call it a proper solution though since as far as I understand it disables the new protection system completely.

**Comment by deanishe** [comment]
Has anyone tried clearing the quarantined attribute on the executable?
