### ISSUE TITLE
Can't open iTerm2

### ISSUE THREAD

**Issue by LarkinZero** [deanishe/alfred-ssh#27]
Alfred version is 4.0.5 1118
It will open chrome.
Weird.
![屏幕录制2019-10-24上午11 17 47](https://user-images.githubusercontent.com/6387162/67450572-63947100-f650-11e9-8978-470a56a489a1.gif)

**Comment by LarkinZero** [comment]
I found alfred-ssh will log this
`13:52:53 assh.go:295: Command: /usr/bin/open [open ssh://jenkins]`
So i changed default ssh scheme handler in iTerm2,it works!
<img width="1007" alt="Xnip2019-10-30_13-50-55" src="https://user-images.githubusercontent.com/6387162/67832369-6560a780-fb1c-11e9-9af3-ffa72e0bc10f.png">

**Comment by deanishe** [comment]
> So i changed default ssh scheme handler in iTerm2,it works!

[That is what the instructions say](https://github.com/deanishe/alfred-ssh#using-iterm2).
