### ISSUE TITLE
Option to load config from ~/.ssh/config.d/* folder

### ISSUE THREAD

**Issue by nklmilojevic** [deanishe/alfred-ssh#3]
As of OpenSSH 7.3, there's an Include option in .ssh/config file that reads the folder that you set in .ssh/config with Include .ssh/config.d for example. It would be nice if you can add a possibility to use custom folder.

Thanks

**Comment by deanishe** [comment]
Might be worth requesting that [upstream at the SSH config parser library I'm using](https://github.com/havoc-io/ssh_config).

**Comment by danieljimenez** [comment]
Hi, I've forked the above and added support for Include: https://github.com/danieljimenez/ssh_config
