### ISSUE TITLE
Notarise binaries

### ISSUE THREAD

**Issue by rossburton** [deanishe/alfred-ssh#39]
As other bugs have discussed, with Catalina macOS will refuse to run the helper binaries.  However the other bugs are closed as there is nothing you can do, but this is incorrect (as clearly macos binaries *can* be distributed).

https://github.com/mitchellh/gon is a tool to help notarise Go binaries. Once the binary is notarised macOS won't complain about the binaries.

**Comment by deanishe** [comment]
> there is nothing you can do

I am not paying Apple €99/year to be able to sign open-source software for their platform. End of discussion. Should I sign up for a paid developer account for other reasons, I will sign the binaries.
