### ISSUE TITLE
Problems deleting connections from history

### ISSUE THREAD

**Issue by durzel** [deanishe/alfred-ssh#4]
I'm having problems deleting connections from my history.  I hold down Control and press Return (or click) on the connection I want to delete, the subheader says "Delete connection from history", but when pressing Return the list of connections just refreshes with no change to them (i.e. connection is not deleted).

I'm running the latest version 0.7.1 on a 2017 MacBook Pro 15" with Touch Bar.

**Comment by deanishe** [comment]
Silly error by me. If you crack open the lilac Run Script action titled **Alternate Action: Forget connection from History** and change this:

```
# Remove URL from History
./assh forget "$name" "$url"
```
to this:

```
# Remove URL from History
./assh forget "$url"
```

it works as intended.

**Comment by durzel** [comment]
Thanks, that works like a charm.  Sorry for the delay responding.
