### ISSUE TITLE
Alfred4 I set 2 Host in my ssh config file, but no matter which I choose in Alfred  It always  open the only one

### ISSUE THREAD

**Issue by LimnN** [deanishe/alfred-ssh#49]

**Comment by LimnN** [comment]
Here is my config file, no matter I ssh hoxxx or ssh tenxxx in Alfred, it always open the txxxxx one.
<img width="749" alt="截屏2020-07-10 01 54 30" src="https://user-images.githubusercontent.com/14120609/87073799-87382f80-c250-11ea-830c-1af4097d1e3a.png">

**Comment by deanishe** [comment]
> it always open the txxxxx one

What do you mean? The workflow is generating an incorrect URL? Check Alfred's debugger to see what URL the workflow is generating.

**Comment by LimnN** [comment]
well, I've fix it by reset my iterm...
