### ISSUE TITLE
Setting a default user so I don't have to type it every time

### ISSUE THREAD

**Issue by alexgurr** [deanishe/alfred-ssh#5]
Whenever I SSH into any IP, every time, I have to use a different user (different than the one I'm logged in as). I can type 'ssh user@' to get the same list of IPs, but it would be useful if I could set a default user, so I don't have to type it every time. Any thoughts?

Regards,
Alex

**Comment by deanishe** [comment]
If it's always the same username, can you not put this in your `~/.ssh/config`?

```
Match Host *
    User bob
```

**Comment by alexgurr** [comment]
Worked perfectly - thanks.
