### ISSUE TITLE
Does not show connections with `-` in name

### ISSUE THREAD

**Issue by selfish** [deanishe/alfred-ssh#6]
When name in `~/.ssh/config` has a `-` in title, it will not appear in list on alfred
```
Host example-example-example
    User ...
    HostName ...
    UseKeychain yes
    AddKeysToAgent yes
    IdentityFile ...
```

**Comment by deanishe** [comment]
It works just fine for me. Which version of the workflow are you using?

**Comment by selfish** [comment]
v0.7.2

I re-tested the issue and I can't reproduce.
I can swear I tried and tried, but whatever. Thanks anyway, and sorry for your time.
